In [2]:
!pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.20.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.2)
Requirement already satisfied: protobuf>=5.28.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.2.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.82.1)
Requirement already satisfied: tensorboard~=2.20.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.16.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.19.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.6.17)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.10.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (11.3.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.1.8)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.2)

In [3]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , OneHotEncoder
from sklearn.compose import ColumnTransformer

df = pd.read_csv('Churn_Modelling.csv')
df.head()
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

(10000, 14)

In [4]:
df.duplicated().sum()
df.head(10)
y = df.iloc[:, 13]
x = df.drop(['Exited', 'CustomerId', 'Surname','RowNumber'], axis=1)
x['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'EstimatedSalary']),
        ('cat', OneHotEncoder(), ['Geography', 'Gender'])
    ])
x_train = preprocessor.fit_transform(x_train)
x_test = preprocessor.transform(x_test)

# x_train = np.asarray(x_train).astype(np.float32)
# x_test = np.asarray(x_test).astype(np.float32)
y.unique()
#

array([1, 0])

In [6]:
model = keras.Sequential([
    layers.Input(shape=(x_train.shape[1],)),
    layers.Dense(64, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(16, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
traing_val = model.fit(x_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

train_loss, train_accuracy = model.evaluate(x_train, y_train)


loss, accuracy = model.evaluate(x_test, y_test)
print(f"Test Loss: {loss:.4f}, Test Accuracy: {accuracy:.4f}")

print(f"Train Loss: {train_loss:.4f}, Train Accuracy: {train_accuracy:.4f}")

Epoch 1/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - accuracy: 0.7969 - loss: 0.4702 - val_accuracy: 0.8331 - val_loss: 0.3980
Epoch 2/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8333 - loss: 0.3842 - val_accuracy: 0.8531 - val_loss: 0.3545
Epoch 3/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8428 - loss: 0.3651 - val_accuracy: 0.8625 - val_loss: 0.3493
Epoch 4/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8464 - loss: 0.3584 - val_accuracy: 0.8550 - val_loss: 0.3484
Epoch 5/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8487 - loss: 0.3543 - val_accuracy: 0.8606 - val_loss: 0.3392
Epoch 6/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.8511 - loss: 0.3517 - val_accuracy: 0.8587 - val_loss: 0.3383
Epoch 7/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.8494 - loss: 0.3495 - val_accuracy: 0.8625 - val_loss: 0.3391
Epoch 8/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - accuracy: 0.8494 - loss: 0.3460 - val_accuracy: 0.8594 - val_loss: 0.3359
Epoch 9/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8511 - loss: 0.3438 - val_accuracy: 0.8550 - val_loss: 0.3369
Epoch 10/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8545 - loss: 0.3428 - val_accuracy: 0.8600 - val_loss: 0.3347
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8572 - loss: 0.3339
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8520 - loss: 0.3569
Test Loss: 0.3569, Test Accuracy: 0.8520
Train Loss: 0.3339, Train Accuracy: 0.8572

Second model

In [9]:
df = pd.read_csv('bengaluru_house_prices.csv')
df.head(10)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,DuenaTa,1170,2.0,1.0,38.00
6,Super built-up Area,18-May,Old Airport Road,4 BHK,Jaades,2732,4.0,NaN,204.00
7,Super built-up Area,Ready To Move,Rajaji Nagar,4 BHK,Brway G,3300,4.0,NaN,600.00
8,Super built-up Area,Ready To Move,Marathahalli,3 BHK,NaN,1310,3.0,1.0,63.25
9,Plot Area,Ready To Move,Gandhi Bazar,6 Bedroom,NaN,1020,6.0,NaN,370.00

In [19]:
#df.drop('society',axis=1,inplace=True)
df.info()
df.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   total_sqft    13320 non-null  object
 5   bath          13247 non-null  float64
 6   balcony       12711 non-null  float64
 7   price         13320 non-null  float64
dtypes: float64(3), object(5)
memory usage: 832.6+ KB

,area_type,availability,location,size,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200,2.0,1.0,51.00
5,Super built-up Area,Ready To Move,Whitefield,2 BHK,1170,2.0,1.0,38.00
6,Super built-up Area,18-May,Old Airport Road,4 BHK,2732,4.0,NaN,204.00
7,Super built-up Area,Ready To Move,Rajaji Nagar,4 BHK,3300,4.0,NaN,600.00
8,Super built-up Area,Ready To Move,Marathahalli,3 BHK,1310,3.0,1.0,63.25
9,Plot Area,Ready To Move,Gandhi Bazar,6 Bedroom,1020,6.0,NaN,370.00

In [67]:

# حذف الأعمدة اللي مش هتفيدك أو صعبة (availability فيها تواريخ مخلوطة)
# df = df.drop(['availability'], axis=1)

# التعامل مع الـ size
# df['bhk'] = df['size'].apply(lambda x: int(str(x).split(' ')[0]) if pd.notnull(x) else np.nan)
# df = df.drop(['size'], axis=1)

# التعامل مع total_sqft (فيها ranges زي "2100-2850")
def convert_sqft(x):
    try:
        tokens = str(x).split('-')
        if len(tokens) == 2:
            return (float(tokens[0]) + float(tokens[1])) / 2
        return float(x)
    except:
        return None

df['total_sqft'] = df['total_sqft'].apply(convert_sqft)

df['location'] = df['location'].apply(lambda x: str(x).strip())
location_counts = df['location'].value_counts()
rare_locations = location_counts[location_counts <= 10].index
df['location'] = df['location'].apply(lambda x: 'other' if x in rare_locations else x)

# حذف الصفوف اللي فيها missing values مهمة
df['balcony'] = df['balcony'].fillna(df['balcony'].median())
df['price'] = df['price'].fillna(df['price'].mean())
df['bath'] = df['bath'].fillna(df['bath'].mean())
df['bhk'] = df['bhk'].fillna(df['bhk'].mean())
df['total_sqft'] = df['total_sqft'].fillna(df['total_sqft'].mean())

In [58]:

df_encoded = pd.get_dummies(df, columns=['area_type', 'location'], drop_first=True)

X = df_encoded.drop('price', axis=1)
y = df_encoded['price']

         total_sqft          bath       balcony         price           bhk
count  12564.000000  12564.000000  12564.000000  12564.000000  12564.000000
mean    1592.005471      2.555874      1.603231    111.338732      2.648122
std     1256.001909      1.062250      0.796549    151.866849      0.959307
min      300.000000      1.000000      0.000000      8.440000      1.000000
25%     1117.000000      2.000000      1.000000     49.000000      2.000000
50%     1300.000000      2.000000      2.000000     70.000000      3.000000
75%     1700.000000      3.000000      2.000000    115.000000      3.000000
max    52272.000000     14.000000      3.000000   3600.000000     10.000000

In [68]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# مهم جداً في Neural Networks: الـ Scaling
scaler_X = StandardScaler()
X_train_scaled = scaler_X.fit_transform(X_train)
X_test_scaled = scaler_X.transform(X_test)


# لو الـ price متباعدة قيمها جداً، ممكن تسكيلها برضو (اختياري بس بيحسن التدريب)
# scaler_y = StandardScaler()
# y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1))
# y_test_scaled = scaler_y.transform(y_test.values.reshape(-1, 1))

In [69]:

model = models.Sequential([
    layers.Input(shape=(X_train_scaled.shape[1],)),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(64, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(32, activation='relu'),
    layers.Dense(1, activation='linear')  # زي ما شرحنا، Linear للـ Regression
])

model.compile(
    optimizer='adam',
    loss='mse',           # Mean Squared Error
    metrics=['mae']        # Mean Absolute Error عشان تتابع بيه
)

model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_32 (Dense)                │ (None, 128)            │        29,568 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_14 (Dropout)            │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_33 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_15 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_34 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_35 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 39,937 (156.00 KB)

 Trainable params: 39,937 (156.00 KB)

 Non-trainable params: 0 (0.00 B)

In [70]:
history = model.fit(
    X_train_scaled, y_train,
    validation_split=0.2,
    epochs=30,
    batch_size=32,
    callbacks=[
        tf.keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True)
    ],
    verbose=1
)

Epoch 1/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 18565.1621 - mae: 64.2252 - val_loss: 14456.7363 - val_mae: 51.2410
Epoch 2/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13355.4258 - mae: 46.2136 - val_loss: 13942.3359 - val_mae: 43.3132
Epoch 3/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 12864.2559 - mae: 43.5785 - val_loss: 13786.5605 - val_mae: 41.9497
Epoch 4/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 12480.1182 - mae: 43.2813 - val_loss: 13861.0820 - val_mae: 40.3746
Epoch 5/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11769.8496 - mae: 41.8975 - val_loss: 13571.3398 - val_mae: 40.7115
Epoch 6/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11754.2061 - mae: 42.1321 - val_loss: 13686.0049 - val_mae: 40.6782
Epoch 7/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11494.0400 - mae: 41.6790 - val_loss: 13601.6816 - val_mae: 39.4717
Epoch 8/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11484.2783 - mae: 40.6084 - val_loss: 13355.2852 - val_mae: 38.8537
Epoch 9/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 10727.2998 - mae: 40.0149 - val_loss: 13319.3945 - val_mae: 38.1044
Epoch 10/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 11284.0674 - mae: 40.6154 - val_loss: 13479.0088 - val_mae: 38.6914
Epoch 11/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 10672.3340 - mae: 39.9306 - val_loss: 13225.2939 - val_mae: 38.1021
Epoch 12/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10380.2393 - mae: 39.3792 - val_loss: 13536.4092 - val_mae: 38.3888
Epoch 13/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10256.0010 - mae: 39.1934 - val_loss: 13098.7949 - val_mae: 38.1305
Epoch 14/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10332.0703 - mae: 39.1597 - val_loss: 13140.7812 - val_mae: 38.2148
Epoch 15/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9866.7783 - mae: 39.3816 - val_loss: 13072.4297 - val_mae: 37.6956
Epoch 16/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9541.1133 - mae: 38.8768 - val_loss: 13130.5791 - val_mae: 37.5142
Epoch 17/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9237.1533 - mae: 38.6588 - val_loss: 12946.9424 - val_mae: 37.3263
Epoch 18/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9725.0078 - mae: 38.7795 - val_loss: 13249.9980 - val_mae: 38.6903
Epoch 19/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9364.1787 - mae: 38.5177 - val_loss: 12573.5420 - val_mae: 37.1556
Epoch 20/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9172.6611 - mae: 38.1694 - val_loss: 13744.8271 - val_mae: 38.8433
Epoch 21/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9152.2217 - mae: 38.7359 - val_loss: 13396.5039 - val_mae: 39.6674
Epoch 22/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9443.5996 - mae: 38.4902 - val_loss: 12577.1875 - val_mae: 37.5714
Epoch 23/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 8631.4727 - mae: 37.8077 - val_loss: 12590.6006 - val_mae: 38.3641
Epoch 24/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 9220.8213 - mae: 38.1307 - val_loss: 12228.4160 - val_mae: 36.8648
Epoch 25/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 8339.3184 - mae: 37.5400 - val_loss: 12974.9717 - val_mae: 40.1720
Epoch 26/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9124.9824 - mae: 37.7807 - val_loss: 12128.3428 - val_mae: 37.4397
Epoch 27/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8596.6494 - mae: 37.6107 - val_loss: 12255.1523 - val_mae: 38.2397
Epoch 28/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8446.2139 - mae: 37.6041 - val_loss: 12342.4229 - val_mae: 38.0992
Epoch 29/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 8757.9570 - mae: 37.7004 - val_loss: 12451.0273 - val_mae: 36.6128
Epoch 30/30
252/252 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7976.4106 - mae: 36.8850 - val_loss: 12558.0576 - val_mae: 37.9478

In [71]:
from sklearn.metrics import mean_absolute_error, r2_score

y_pred = model.predict(X_test_scaled)
# y_pred = scaler_y.inverse_transform(y_pred_scaled)
# y_test_actual = scaler_y.inverse_transform(y_test_scaled)

print("MAE:", mean_absolute_error(y_test, y_pred))
print("R² Score:", r2_score(y_test, y_pred))

79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
MAE: 33.2674284902285
R² Score: 0.6350103978218715